### ISSUE TITLE
Pasting on Mac not working on 1.4.x (keep complaining about missing Accessibility permission)

### ISSUE THREAD

**Issue by dazworker** [Rainclip/Rainclip-Issues#21]
Hi, for me, pasting doesn't work on Mac with the 1.4.x versions (first 1.4.101 and now 1.4.102) and they keep complaining about the accessibility permission missing.

Various combinations of disabling and re-enabling, removing and re-adding the permission when prompted by Rainclip, uninstalling and re-installing Rainclip and rebooting did not help.

Everything works fine when going back to 1.3.100.

2021 MBP M1 Max with Monterey 12.2.1 at first, I just upgraded to 12.3, no success there either.

I'm pretty happy with Rainclip otherwise, it replaced Ditto on Windows for me and it's very nice to be able to use the same tool across OSes.

**Comment by Rainclip** [comment]
This should be now fixed in 1.4.103

**Comment by dazworker** [comment]
Works fine now, thanks a lot for the quick fix :)
