### ISSUE TITLE
Google sync broken in Windows version 1.4.102

### ISSUE THREAD

**Issue by monster1612** [Rainclip/Rainclip-Issues#22]
I've been trying to connect Rainclip to my Google account on a new Windows 11 install (Insider x64, build 22533), but I've noticed that even though I see in the browser that the authorization succeeded and that I can close the tab, Rainclip only continues to show a spinning icon with no indication that the sync is succeeding. I have made sure that Rainclip is allowed as an exception in Windows Firewall, and I know for a fact that sync succeeds with version 1.2.99 (but I've also noticed that if I upgrade in-place to 1.4.102 from there, sync also fails; I tested on both that same machine and another Windows 11 install running build 22572).

here's a [debug log](https://github.com/Rainclip/Rainclip-Issues/files/8307140/Rainclip-debug-log.txt) from version 1.4.102 (I censored the callback code and other sensitive info) after trying to reproduce the initial authorization issue. hope this helps.

**Comment by Rainclip** [comment]
There are two issues related to this. The recent Qt upgrade broke error handling in network operations which is the reason the progress spinner never stops. The other issue is related to the OpenSSL library which doesn't work for some reason when Rainclip is installed but everything works fine on my development environment. I'll check what's causing this.

**Comment by Rainclip** [comment]
This should be now fixed in 1.4.104
