### ISSUE TITLE
(Suggestion) Allow post-snippet cursor/input placement

### ISSUE THREAD

**Issue by SEMilfred** [Rainclip/Rainclip-Issues#7]
I don't know if it is at all possible, but it would be a great improvement for people like me (programmers), if we could mark a part of a snippet as being the selected text when the snippet is inserted.

For example, a snippet could look like `/// @function			|function|();` and as the snippet is inserted, the bit marked with `|`'s would be instantly highlighted/selected.

**Comment by Li-An** [comment]
+1

**Comment by Rainclip** [comment]
At least in theory it is possible but the cursor needs to be moved one character at a time so I'm not sure how well it works with large snippets. I'll try and see.

**Comment by Rainclip** [comment]
This is now possible in v1.1
